### PR TITLE
Bumps in ionic : ci_matching_branch/bump_ionic_gz-fuel-tools10

### PR DESCRIPTION
**Pull request by azeey**
See https://github.com/gazebo-tooling/release-tools/issues/1027

### CODE REVIEW

**Review by iche033 — APPROVED** [review]

**Comment by iche033** [comment]
revert bump to gz-tools?

**Review by iche033 — APPROVED** [review]

**Comment by azeey** [comment]
Test: [Build Status](https://build.osrfoundation.org/job/gz-fuel-tools10-debbuilder/1/)

**Comment by iche033** [comment]
Test: [Build Status](https://build.osrfoundation.org/job/gz-fuel-tools10-debbuilder/2/)

**Comment by iche033** [comment]
Test: [Build Status](https://build.osrfoundation.org/job/gz-fuel-tools10-debbuilder/3/)

**Comment by azeey** [comment]
Thanks @iche033

**Pull request merged**
